# Generated by Django 4.1 on 2023-02-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="healthworker",
            name="Phonenumber",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="pnonenumber",
        ),
        migrations.AddField(
            model_name="healthworker",
            name="email",
            field=models.EmailField(
                max_length=254, null=True, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AddField(
            model_name="healthworker",
            name="phone number",
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="email",
            field=models.EmailField(
                max_length=254, null=True, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="phone number",
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
